language: node_js

node_js:
  - '4'
  - '5'
  - '6'
  - '7'

notifications:
  email:
    on_success: never
    on_failure: always

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

test:
  - yarn lint
