"use strict"

module.exports = {
  "rulesDirectory": [
    "node_modules/codelyzer",
  ],
  "rules": {
    /**
     * TypeScript Specific
     */
    "adjacent-overload-signatures": true,
    "member-access": false,
    "member-ordering": [
      true,
      {
        "alphabetize": false,
        "order": [
          "public-static-field",
          "public-static-method",
          "protected-static-field",
          "protected-static-method",
          "private-static-field",
          "private-static-method",
          "public-instance-field",
          "protected-instance-field",
          "private-instance-field",
          "public-constructor",
          "protected-constructor",
          "private-constructor",
          "public-instance-method",
          "protected-instance-method",
          "private-instance-method",
        ],
      },
    ],
    "no-any": true,
    "no-empty-interface": true,
    "no-import-side-effect": true,
    "no-inferrable-types": [false],
    "no-internal-module": true,
    "no-magic-numbers": true,
    "no-namespace": true,
    "no-non-null-assertion": true,
    "no-reference": true,
    "no-var-requires": true,
    "only-arrow-functions": [true],
    "prefer-for-of": true,
    "typedef": [ true,
      "call-signature",
      "parameter",
      "property-declaration",
      "member-variable-declaration",
    ],
    "typedef-whitespace": [
      true,
      {
        "call-signature": "nospace",
        "index-signature": "nospace",
        "parameter": "nospace",
        "property-declaration": "nospace",
        "variable-declaration": "nospace",
      },
      {
        "call-signature": "space",
        "index-signature": "space",
        "parameter": "space",
        "property-declaration": "space",
        "variable-declaration": "space",
      },
    ],
    "unified-signatures": true,

    /**
     * Functionality
     */
    "await-promise": false,
    "ban": false,
    "curly": true,
    "forin": true,
    "import-blacklist": [ true, "rxjs" ],
    "label-position": true,
    "no-arg": true,
    "no-bitwise": true,
    "no-conditional-assignment": true,
    "no-console": [
      true,
      "debug",
      "info",
      "time",
      "timeEnd",
      "trace",
    ],
    "no-construct": true,
    "no-debugger": true,
    "no-duplicate-super": true,
    "no-duplicate-variable": true,
    "no-empty": true,
    "no-eval": true,
    "no-invalid-this": true,
    "no-misused-new": true,
    "no-null-keyword": false,
    "no-shadowed-variable": true,
    "no-string-literal": true,
    "no-string-throw": true,
    "no-switch-case-fall-through": true,
    "no-unsafe-finally": true,
    "no-unused-expression": true,
    "no-unused-new": true,
    "no-use-before-declare": true,
    "no-var-keyword": true,
    "radix": true,
    "switch-default": true,
    "triple-equals": [
      true,
      "allow-null-check",
    ],
    "typeof-compare": true,
    "use-isnan": true,

    /**
     * Maintainability
     */
    "cyclomatic-complexity": [ true, 10 ],
    "eofline": true,
    "indent": [
      true,
      "spaces",
    ],
    "linebreak-style": [ true, "LF" ],
    "max-classes-per-file": [ true, 1 ],
    "max-file-line-count": [ true, 250 ],
    "max-line-length": [ true, 120 ],
    "no-default-export": true,
    "no-mergeable-namespace": true,
    "no-require-imports": true,
    "object-literal-sort-keys": true,
    "prefer-const": true,
    "trailing-comma": [
      true,
      {
        "multiline": false,
        "singleline": "never",
      },
    ],

    /**
     * Style
     */
    "align": [ true, "statements" ],
    "array-type": [ true, "array" ],
    "arrow-parens": [false],
    "arrow-return-shorthand": [true],
    "callable-types": false,
    "class-name": true,
    "comment-format": [
      true,
      "check-space",
    ],
    "completed-docs": [false],
    "file-header": [false],
    "import-spacing": true,
    "interface-name": [false],
    "interface-over-type-literal": true,
    "jsdoc-format": true,
    "newline-before-return": false,
    "new-parens": true,
    "no-angle-bracket-type-assertion": true,
    "no-consecutive-blank-lines": [ true, 2 ],
    "no-parameter-properties": false,
    "no-trailing-whitespace": true,
    "no-unnecessary-initializer": true,
    "object-literal-key-quotes": [ true, "as-needed" ],
    "object-literal-shorthand": true,
    "one-line": [
      true,
      "check-catch",
      "check-else",
      "check-finally",
      "check-open-brace",
      "check-whitespace",
    ],
    "one-variable-per-declaration": [ true, "ignore-for-loop" ],
    "ordered-imports": [false],
    "prefer-function-over-method": [false],
    "prefer-method-signature": true,
    "quotemark": [
      true,
      "single",
      "avoid-escape",
    ],
    "semicolon": [ true, "always" ],
    "space-before-function-paren": [ true, "never" ],
    "variable-name": [
      true,
      "check-format",
      "ban-keywords",
    ],
    "whitespace": [
      true,
      "check-branch",
      "check-decl",
      "check-operator",
      "check-module",
      "check-separator",
      "check-type",
      "check-typecast",
    ],

    /**
     * CodeLyzer
     */
    "directive-selector": [ true, "attribute", "smt", "camelCase" ],
    "component-selector": [ true, "element", "smt", "kebab-case" ],
    "use-input-property-decorator": true,
    "use-output-property-decorator": true,
    "use-host-property-decorator": true,
    "no-attribute-parameter-decorator": true,
    "no-input-rename": true,
    "no-output-rename": true,
    "no-forward-ref": true,
    "use-life-cycle-interface": true,
    "use-pipe-transform-interface": true,
    "pipe-naming": [ true, "camelCase", "smt" ],
    "component-class-suffix": true,
    "directive-class-suffix": true,
    "templates-use-public": true,
    "no-access-missing-member": true,
    "invoke-injectable": true,
  },
}
